name: Calificar código Python

on:
  push:
    paths:
      - 'Student/**'

jobs:
  calificar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Calificar con pytest
        run: |
          pytest --doctest-modules test/test_01.py Student/${{ github.event.head_commit.author.name }}_*/actividad_01.py

